# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Build and run integration tests

on:
  push:
    branches:
      - main
      - cicd-builds
  pull_request_target:
    branches: [ "main" ]

env:
  S3_TEST_REGION :  ${{ vars.S3_TEST_REGION }}
  S3_TEST_BUCKET : ${{ vars.S3_TEST_BUCKET }}
  S3_TEST_PREFIX : ${{ vars.S3_TEST_PREFIX }}
  ROLE_TO_ASSUME: ${{ secrets.S3_TEST_ASSUME_ROLE_ARN }}

jobs:
  build:
    name: Integration Tests
    runs-on: codebuild-s3-analytics-accelerator-eu-west-1-${{ github.run_id }}-${{ github.run_attempt }}
    environment: integration-tests
    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

    - name: Configure aws credentials
      uses: aws-actions/configure-aws-credentials@v4.0.2
      with:
        role-to-assume: ${{ env.ROLE_TO_ASSUME }}
        role-session-name: GitHub_to_AWS_via_FederatedOIDC
        aws-region: ${{ env.S3_TEST_REGION }}

    - name: Build with Gradle Wrapper
      run: ./gradlew integrationTest


